### ISSUE TITLE
Ordering of digits in extra_long_mult.cpp

### ISSUE THREAD

**Issue by Gopal9816** [BedirT/AlgorithmsL#3]
In the program [extra_long_mult.cpp](https://github.com/BedirT/Algorithms_and_DS/blob/master/Algorithms/Math/extra_long_mult.cpp), how are the digits in the input strings arranged i.e is the lowest position digit the first digit (big endian) or is the highest position digit first (little endian). 

For a normal input (i.e little endian), shouldn't we traverse the array from right to left while adding the carryover like below
```
for (i = 0; i < str2.size() ; ++i)
        for (j = 0; j < str1.size() ; ++j)
            mul[i+j+1] += num2[i] * num1[j];
 
for (i = maxLen; i >0 ; --i){
        mul[i-1] += mul[i]/10;
        mul[i] %= 10;
} 
```

**Comment by BedirT** [comment]
Yes, I made a mistake apparently, thanks for clearing out.
