### ISSUE TITLE
issue in some test cases like:

### ISSUE THREAD

**Issue by gods-mack** [BedirT/AlgorithmsL#6]
999+20 = ?
999+2 = ?
2893876287 + 37 = ?

**Comment by BedirT** [comment]
Which file are you having problem with ?

**Comment by gods-mack** [comment]
https://github.com/BedirT/Algorithms_and_DS/blob/master/Algorithms/Math/extra_long_sum.cpp

**Comment by BedirT** [comment]
Well, by default, c++ should be allocating 0 to initial array values for int, I don't really know why it wasn't, I fixed the issue ( a bit messier but not much change) 

Thanks for pointing out.
